openapi: 3.0.3
info:
  title: Example API
  version: 0.1.0
paths:
  /api/license/activate:
    post:
      operationId: licenseActivate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/license.activate.request.json'
      responses:
        '200':
          description: OK
